version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/html/bluebonnet/
hooks:
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
  AfterInstall:
    - location: deploy/restart_server
      timeout: 300
