version: 0.0
os: linux
files:
  - source: public/index.php
    destination: /var/www/html/bluebonnet/public
hooks:
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deploy/restart_server
      timeout: 300
      runas: ubuntu
